CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Parcels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Weight" numeric(5,2) NOT NULL,
    "Type" text NOT NULL,
    CONSTRAINT "PK_Parcels" PRIMARY KEY ("Id")
);

CREATE TABLE "Terminals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Address" character varying(255) NOT NULL,
    "Region" character varying(100) NOT NULL,
    "Type" text NOT NULL,
    CONSTRAINT "PK_Terminals" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Clients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "PhoneNumber" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "Address" character varying(100) NOT NULL,
    "ApplicationUserId" text,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Clients_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "Employees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Position" text NOT NULL,
    "PhoneNumber" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "ApplicationUserId" text,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Employees_AspNetUsers_ApplicationUserId" FOREIGN KEY ("ApplicationUserId") REFERENCES "AspNetUsers" ("Id")
);

CREATE TABLE "PostOffices" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Address" character varying(255) NOT NULL,
    "City" character varying(100) NOT NULL,
    "PhoneNumber" character varying(20) NOT NULL,
    "TerminalId" integer,
    CONSTRAINT "PK_PostOffices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PostOffices_Terminals_TerminalId" FOREIGN KEY ("TerminalId") REFERENCES "Terminals" ("Id")
);

CREATE TABLE "TerminalEmployees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "TerminalId" integer NOT NULL,
    CONSTRAINT "PK_TerminalEmployees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TerminalEmployees_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TerminalEmployees_Terminals_TerminalId" FOREIGN KEY ("TerminalId") REFERENCES "Terminals" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PostOfficeEmployees" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EmployeeId" integer NOT NULL,
    "PostOfficeId" integer NOT NULL,
    CONSTRAINT "PK_PostOfficeEmployees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PostOfficeEmployees_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PostOfficeEmployees_PostOffices_PostOfficeId" FOREIGN KEY ("PostOfficeId") REFERENCES "PostOffices" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Shipments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SenderId" integer NOT NULL,
    "ReceiverId" integer NOT NULL,
    "FromPostOfficeId" integer NOT NULL,
    "ToPostOfficeId" integer NOT NULL,
    "ParcelId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "DeliveredAt" timestamp with time zone,
    "Status" text NOT NULL,
    CONSTRAINT "PK_Shipments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shipments_Clients_ReceiverId" FOREIGN KEY ("ReceiverId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Shipments_Clients_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Shipments_Parcels_ParcelId" FOREIGN KEY ("ParcelId") REFERENCES "Parcels" ("Id"),
    CONSTRAINT "FK_Shipments_PostOffices_FromPostOfficeId" FOREIGN KEY ("FromPostOfficeId") REFERENCES "PostOffices" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Shipments_PostOffices_ToPostOfficeId" FOREIGN KEY ("ToPostOfficeId") REFERENCES "PostOffices" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_Clients_ApplicationUserId" ON "Clients" ("ApplicationUserId");

CREATE UNIQUE INDEX "IX_Clients_PhoneNumber" ON "Clients" ("PhoneNumber");

CREATE UNIQUE INDEX "IX_Employees_ApplicationUserId" ON "Employees" ("ApplicationUserId");

CREATE UNIQUE INDEX "IX_Employees_PhoneNumber" ON "Employees" ("PhoneNumber");

CREATE UNIQUE INDEX "IX_PostOfficeEmployees_EmployeeId" ON "PostOfficeEmployees" ("EmployeeId");

CREATE INDEX "IX_PostOfficeEmployees_PostOfficeId" ON "PostOfficeEmployees" ("PostOfficeId");

CREATE INDEX "IX_PostOffices_TerminalId" ON "PostOffices" ("TerminalId");

CREATE INDEX "IX_Shipments_FromPostOfficeId" ON "Shipments" ("FromPostOfficeId");

CREATE UNIQUE INDEX "IX_Shipments_ParcelId" ON "Shipments" ("ParcelId");

CREATE INDEX "IX_Shipments_ReceiverId" ON "Shipments" ("ReceiverId");

CREATE INDEX "IX_Shipments_SenderId" ON "Shipments" ("SenderId");

CREATE INDEX "IX_Shipments_ToPostOfficeId" ON "Shipments" ("ToPostOfficeId");

CREATE UNIQUE INDEX "IX_TerminalEmployees_EmployeeId" ON "TerminalEmployees" ("EmployeeId");

CREATE INDEX "IX_TerminalEmployees_TerminalId" ON "TerminalEmployees" ("TerminalId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250418211203_InitialCreate', '9.0.4');

ALTER TABLE "Clients" ADD "City" character varying(100) NOT NULL DEFAULT '';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250419214513_AddedCityToClient', '9.0.4');

ALTER TABLE "Terminals" RENAME COLUMN "Region" TO "City";

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250420170546_TerminalsChangedRegionToCity', '9.0.4');

ALTER TABLE "Shipments" ADD "Price" double precision NOT NULL DEFAULT 0.0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250429182857_AddPriceToShipment', '9.0.4');

COMMIT;

